### PR TITLE
Gem'ed

### PR DESCRIPTION
**Pull request by ebertech**
Hi

So, I've packaged this up into a gem. The commands are:

request-log-analyzer-munin install

and

request-log-analyzer-munin add app_name path_to_log

I'm sure this thing could be made nicer with options to pass in the ruby path and so on... but it's a start. What do you think?

### CODE REVIEW

**Comment by barttenbrinke** [comment]
Hi there,

nice work! I've been meaning to put this into a gem for quite some time :)
I've tried to pull your changes, but somehow github says they won't apply cleanly.
As I'm currently on a fair, I will merge stuff this weekend.

Greetings, Bart

**Comment by ebertech** [comment]
Ok sounds good.

**Comment by barttenbrinke** [comment]
I'ver merged everything and made you contributer on the repo. I think the readme now needs updating :) Will try to do that this weekend....

**Comment by ebertech** [comment]
sounds good. Want me to update the readme if you didn't get a chance this past weekend? I'm not sure how much you've used munin but gem packaging for munin plugins makes them so much easier to deal with.

**Comment by barttenbrinke** [comment]
Please do :)

**Pull request merged**
